
import { createWorker } from 'tesseract.js';
import { PDFDocument } from 'pdf-lib';

export async function convertOcrPdf(file: File, onProgress?: (progress: number) => void): Promise<Blob> {
    const pdfjsLib = await import('pdfjs-dist');
    if (!pdfjsLib.GlobalWorkerOptions.workerSrc) {
        pdfjsLib.GlobalWorkerOptions.workerSrc = new URL(
            'pdfjs-dist/build/pdf.worker.min.mjs',
            import.meta.url
        ).toString();
    }
    const arrayBuffer = await file.arrayBuffer();
    const pdf = await pdfjsLib.getDocument({ data: arrayBuffer }).promise;
    const numPages = pdf.numPages;

    // Use local Tesseract resources
    const worker = await createWorker('eng', 1, {
        workerPath: '/pdf-utility/tesseract-worker.min.js',
        corePath: '/pdf-utility/tesseract-core.wasm.js',
        langPath: 'https://raw.githubusercontent.com/naptha/tessdata/gh-pages/4.0.0',
    });

    const mergedPdf = await PDFDocument.create();

    for (let i = 1; i <= numPages; i++) {
        const page = await pdf.getPage(i);
        const viewport = page.getViewport({ scale: 2.0 });

        const canvas = document.createElement('canvas');
        const context = canvas.getContext('2d');
        canvas.height = viewport.height;
        canvas.width = viewport.width;

        if (!context) continue;

        await page.render({
            canvasContext: context,
            viewport: viewport,
        } as any).promise;

        const imgData = canvas.toDataURL('image/jpeg', 0.8);

        // Tesseract v7: Request PDF output
        const { data } = await worker.recognize(imgData, {
            pdfTitle: `Page ${i}`
        }, {
            pdf: true
        });

        if (data.pdf) {
            // Load PDF from conversion
            const pdfUint8Array = new Uint8Array(data.pdf);
            const pageDoc = await PDFDocument.load(pdfUint8Array.buffer as ArrayBuffer);
            const [copiedPage] = await mergedPdf.copyPages(pageDoc, [0]);
            mergedPdf.addPage(copiedPage);
        } else {
            // Fallback or skip? For now, we skip if no PDF generated, but warn?
            // Actually, if using 'eng' and image is clear, it should work.
            console.warn(`Page ${i}: No PDF data generated by Tesseract.`);
        }

        if (onProgress) {
            onProgress(Math.round((i / numPages) * 100));
        }
    }

    await worker.terminate();

    const pdfBytes = await mergedPdf.save();
    return new Blob([new Uint8Array(pdfBytes)], { type: 'application/pdf' });
}
